#!/bin/sh

openssl genrsa -out client.key 1024 
openssl rsa -in client.key -out client.pem
openssl req -new -subj '/CN=Mister Client/O=MyTest/C=US'  -key client.key -out client.csr
openssl x509 -req -days 1000 -in client.csr -signkey client.key -out client.crt
